# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/swiftai',
                'doc_host': 'https://m-gopichand.github.io',
                'git_url': 'https://github.com/m-gopichand/swiftai',
                'lib_path': 'swiftai'},
  'syms': {'swiftai.core': {'swiftai.core.foo': ('core.html#foo', 'swiftai/core.py')}}}
